services:
  - type: web
    name: fsmpro
    env: node
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_PORT
        value: 3000
      - key: DB_HOST
        fromDatabase:
          name: fsmpro-mysql
          property: host
      - key: DB_USER
        fromDatabase:
          name: fsmpro-mysql
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: fsmpro-mysql
          property: password
      - key: DB_NAME
        value: fsm_app
      - key: JWT_SECRET
        sync: false

databases:
  - name: fsmpro-mysql
    databaseName: fsm_app
    user: root
    plan: free
